[workspace]
resolver = "2"
members = [
  "cargo-creusot",
  "creusot-rustc",
  "creusot",
  "creusot-contracts",
  "creusot-contracts-proc",
  "creusot-contracts-dummy",
  "creusot-metadata",
  "creusot-dev-config",
  "creusot-install",
  "why3",
  "why3tests",
  "tests",
  "pearlite-syn",
]

[profile.dev]
split-debuginfo = "off"

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"
